OUTFILE = oswan
SDL = sdl/main_od.o sdl/menu.o sdl/hack.o sdl/gfx/SDL_rotozoom.o sdl/drawing.o sdl/input.o
EMU_CORE = emu/cpu/nec.o emu/WS.o emu/WSApu.o emu/WSFileio.c emu/WSRender.o
OBJS = ${SDL} ${EMU_CORE}
CFLAGS = -Os -fomit-frame-pointer -DNOLAYERS -DSMOOTH -DSOUND_ON -DSOUND_EMULATION -DSPEEDHACKS -DKOLIBRI -I./emu -I./sdl
LIBS = -lSDL
include $(MENUETDEV)/makefiles/Makefile_for_program
