#!/bin/sh

mkdir -p opk
cp ./oswan opk/oswan
cp ./icon.png opk/icon.png
cp ./COPYING opk/COPYING
cp ./COPYING opk/MINIZIP-COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Oswan
Comment=WS/WSC emulator
Exec=oswan %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default."$1".desktop

mksquashfs ./opk oswan_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
