#!/bin/sh

mkdir -p ipkg/home/retrofw/emus/oswan
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/emulators
cp ./oswan ipkg/home/retrofw/emus/oswan/oswan
cp ./opk/icon.png ipkg/home/retrofw/emus/oswan/oswan.png

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: Oswan
Version: 20190331
Description: Wonderswan emulator
Section: emus
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/oswan
Depends:
Source: https://github.com/gameblabla/oswan' > control

print '2.0' > debian-binary

print 'title=Oswan
description=Wonderswan Emulator
exec=/home/retrofw/emus/oswan/oswan
clock=600
selectordir=/home/retrofw/roms
selectorfilter=.ws,.wsc,.bin' > home/retrofw/apps/gmenu2x/sections/emulators/oswan

tar -czvf control.tar.gz control --owner=0 --group=0
tar -czvf data.tar.gz home --owner=0 --group=0
ar rv ../oswan.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
